# Site settings
title: Rozwiązywanie zadań z matematyki
description: > # this means to ignore newlines until "baseurl:"
  Ekspresowe rozwiązywanie zadań z matematyki przez zawodowca z ogromnym doświadczeniem. Pomoc w rozwiązywaniu zadań z matematyki. Rozwiązywanie zadań studia. Algebra liniowa. Analiza matematyczna.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

email: 2plus3plus4@gmail.com
youtube_channel_name: MathTube
youtube_channel_id: UCudqHTl0TY7G3CuCT_flW3w
#google_plus_id: 108578977227886816248
telephone: 603 646 830
whatsapp_id: +48 787 866 411
skype_id: live:.cid.2e90019caa72f9e9
facebook_id: Rozwiązywanie-zadań-z-matematyki-ekspresowo-111578667171445

# Build settings
markdown: kramdown
